name: flutter_app
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

# 默认图标库
  cupertino_icons: ^0.1.2
# dio网络框架
  dio: ^1.0.0
# sp及时储存
  shared_preferences: ^0.4.2
# toast
  fluttertoast: ^2.0.7
# 网络状态检查框架
  connectivity: ^0.3.1
# 第三方loading
  flutter_spinkit: ^2.0.1
# 数据存储
  flutter_redux: ^0.5.2
# 消息总线
  event_bus: ^1.0.1
# webView插件
  flutter_webview_plugin: ^0.2.1

#  ========json=========
# json注解
  json_annotation: ^0.2.4



dev_dependencies:
# 编译框架
  build_runner: ^0.7.0
# json序列化
  json_serializable: ^0.5.2

  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - static/images/logo.png
    - static/images/welcome.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
